name: app auto-test with Github Action

on: [push]

env:
  MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PWD: ${{ secrets.MYSQL_PWD }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
    - name: Build container
      run: |
        docker build -t split-money .
    - name: Run app
      run: |
        python app.py
        # docker run -e MYSQL_HOST=$MYSQL_HOST \
        # -e MYSQL_USER=$MYSQL_USER \
        # -e MYSQL_PWD=$MYSQL_PWD \
        # -e MYSQL_DATABASE=$MYSQL_DATABASE \
        # split-money 
